import boto3

exceptions = boto3.client('appmesh').exceptions

ServiceUnavailableException = exceptions.ServiceUnavailableException
ResourceInUseException = exceptions.ResourceInUseException
BadRequestException = exceptions.BadRequestException
LimitExceededException = exceptions.LimitExceededException
TooManyRequestsException = exceptions.TooManyRequestsException
ConflictException = exceptions.ConflictException
InternalServerErrorException = exceptions.InternalServerErrorException
ForbiddenException = exceptions.ForbiddenException
TooManyTagsException = exceptions.TooManyTagsException
NotFoundException = exceptions.NotFoundException
