import boto3

exceptions = boto3.client('cloudwatch').exceptions

DashboardInvalidInputError = exceptions.DashboardInvalidInputError
ResourceNotFound = exceptions.ResourceNotFound
InternalServiceFault = exceptions.InternalServiceFault
InvalidFormatFault = exceptions.InvalidFormatFault
InvalidNextToken = exceptions.InvalidNextToken
InvalidParameterCombinationException = exceptions.InvalidParameterCombinationException
InvalidParameterValueException = exceptions.InvalidParameterValueException
LimitExceededFault = exceptions.LimitExceededFault
MissingRequiredParameterException = exceptions.MissingRequiredParameterException
