import boto3

exceptions = boto3.client('cloudwatch').exceptions

ConcurrentModificationException = exceptions.ConcurrentModificationException
DashboardInvalidInputError = exceptions.DashboardInvalidInputError
ResourceNotFound = exceptions.ResourceNotFound
InternalServiceFault = exceptions.InternalServiceFault
InvalidFormatFault = exceptions.InvalidFormatFault
InvalidNextToken = exceptions.InvalidNextToken
InvalidParameterCombinationException = exceptions.InvalidParameterCombinationException
InvalidParameterValueException = exceptions.InvalidParameterValueException
LimitExceededException = exceptions.LimitExceededException
LimitExceededFault = exceptions.LimitExceededFault
MissingRequiredParameterException = exceptions.MissingRequiredParameterException
ResourceNotFoundException = exceptions.ResourceNotFoundException
