import boto3

exceptions = boto3.client('codepipeline').exceptions

ActionNotFoundException = exceptions.ActionNotFoundException
ActionTypeNotFoundException = exceptions.ActionTypeNotFoundException
ApprovalAlreadyCompletedException = exceptions.ApprovalAlreadyCompletedException
InvalidActionDeclarationException = exceptions.InvalidActionDeclarationException
InvalidApprovalTokenException = exceptions.InvalidApprovalTokenException
InvalidBlockerDeclarationException = exceptions.InvalidBlockerDeclarationException
InvalidClientTokenException = exceptions.InvalidClientTokenException
InvalidJobException = exceptions.InvalidJobException
InvalidJobStateException = exceptions.InvalidJobStateException
InvalidNextTokenException = exceptions.InvalidNextTokenException
InvalidNonceException = exceptions.InvalidNonceException
InvalidStageDeclarationException = exceptions.InvalidStageDeclarationException
InvalidStructureException = exceptions.InvalidStructureException
InvalidWebhookAuthenticationParametersException = exceptions.InvalidWebhookAuthenticationParametersException
InvalidWebhookFilterPatternException = exceptions.InvalidWebhookFilterPatternException
JobNotFoundException = exceptions.JobNotFoundException
LimitExceededException = exceptions.LimitExceededException
NotLatestPipelineExecutionException = exceptions.NotLatestPipelineExecutionException
PipelineExecutionNotFoundException = exceptions.PipelineExecutionNotFoundException
PipelineNameInUseException = exceptions.PipelineNameInUseException
PipelineNotFoundException = exceptions.PipelineNotFoundException
PipelineVersionNotFoundException = exceptions.PipelineVersionNotFoundException
StageNotFoundException = exceptions.StageNotFoundException
StageNotRetryableException = exceptions.StageNotRetryableException
ValidationException = exceptions.ValidationException
WebhookNotFoundException = exceptions.WebhookNotFoundException
