import boto3

exceptions = boto3.client('cognito-sync').exceptions

AlreadyStreamedException = exceptions.AlreadyStreamedException
ConcurrentModificationException = exceptions.ConcurrentModificationException
DuplicateRequestException = exceptions.DuplicateRequestException
InternalErrorException = exceptions.InternalErrorException
InvalidConfigurationException = exceptions.InvalidConfigurationException
InvalidLambdaFunctionOutputException = exceptions.InvalidLambdaFunctionOutputException
InvalidParameterException = exceptions.InvalidParameterException
LambdaThrottledException = exceptions.LambdaThrottledException
LimitExceededException = exceptions.LimitExceededException
NotAuthorizedException = exceptions.NotAuthorizedException
ResourceConflictException = exceptions.ResourceConflictException
ResourceNotFoundException = exceptions.ResourceNotFoundException
TooManyRequestsException = exceptions.TooManyRequestsException
