import boto3

exceptions = boto3.client('comprehendmedical').exceptions

InternalServerException = exceptions.InternalServerException
InvalidEncodingException = exceptions.InvalidEncodingException
InvalidRequestException = exceptions.InvalidRequestException
ResourceNotFoundException = exceptions.ResourceNotFoundException
ServiceUnavailableException = exceptions.ServiceUnavailableException
TextSizeLimitExceededException = exceptions.TextSizeLimitExceededException
TooManyRequestsException = exceptions.TooManyRequestsException
ValidationException = exceptions.ValidationException
