import boto3

exceptions = boto3.client('dynamodb').exceptions

BackupInUseException = exceptions.BackupInUseException
BackupNotFoundException = exceptions.BackupNotFoundException
ConditionalCheckFailedException = exceptions.ConditionalCheckFailedException
ContinuousBackupsUnavailableException = exceptions.ContinuousBackupsUnavailableException
GlobalTableAlreadyExistsException = exceptions.GlobalTableAlreadyExistsException
GlobalTableNotFoundException = exceptions.GlobalTableNotFoundException
IdempotentParameterMismatchException = exceptions.IdempotentParameterMismatchException
IndexNotFoundException = exceptions.IndexNotFoundException
InternalServerError = exceptions.InternalServerError
InvalidRestoreTimeException = exceptions.InvalidRestoreTimeException
ItemCollectionSizeLimitExceededException = exceptions.ItemCollectionSizeLimitExceededException
LimitExceededException = exceptions.LimitExceededException
PointInTimeRecoveryUnavailableException = exceptions.PointInTimeRecoveryUnavailableException
ProvisionedThroughputExceededException = exceptions.ProvisionedThroughputExceededException
ReplicaAlreadyExistsException = exceptions.ReplicaAlreadyExistsException
ReplicaNotFoundException = exceptions.ReplicaNotFoundException
RequestLimitExceeded = exceptions.RequestLimitExceeded
ResourceInUseException = exceptions.ResourceInUseException
ResourceNotFoundException = exceptions.ResourceNotFoundException
TableAlreadyExistsException = exceptions.TableAlreadyExistsException
TableInUseException = exceptions.TableInUseException
TableNotFoundException = exceptions.TableNotFoundException
TransactionCanceledException = exceptions.TransactionCanceledException
TransactionConflictException = exceptions.TransactionConflictException
TransactionInProgressException = exceptions.TransactionInProgressException
