import boto3

exceptions = boto3.client('elasticbeanstalk').exceptions

CodeBuildNotInServiceRegionException = exceptions.CodeBuildNotInServiceRegionException
ElasticBeanstalkServiceException = exceptions.ElasticBeanstalkServiceException
InsufficientPrivilegesException = exceptions.InsufficientPrivilegesException
InvalidRequestException = exceptions.InvalidRequestException
ManagedActionInvalidStateException = exceptions.ManagedActionInvalidStateException
OperationInProgressFailure = exceptions.OperationInProgressFailure
PlatformVersionStillReferencedException = exceptions.PlatformVersionStillReferencedException
ResourceNotFoundException = exceptions.ResourceNotFoundException
ResourceTypeNotSupportedException = exceptions.ResourceTypeNotSupportedException
S3LocationNotInServiceRegionException = exceptions.S3LocationNotInServiceRegionException
S3SubscriptionRequiredException = exceptions.S3SubscriptionRequiredException
SourceBundleDeletionFailure = exceptions.SourceBundleDeletionFailure
TooManyApplicationVersionsException = exceptions.TooManyApplicationVersionsException
TooManyApplicationsException = exceptions.TooManyApplicationsException
TooManyBucketsException = exceptions.TooManyBucketsException
TooManyConfigurationTemplatesException = exceptions.TooManyConfigurationTemplatesException
TooManyEnvironmentsException = exceptions.TooManyEnvironmentsException
TooManyPlatformsException = exceptions.TooManyPlatformsException
TooManyTagsException = exceptions.TooManyTagsException
