import boto3

exceptions = boto3.client('elb').exceptions

AccessPointNotFoundException = exceptions.AccessPointNotFoundException
CertificateNotFoundException = exceptions.CertificateNotFoundException
DependencyThrottleException = exceptions.DependencyThrottleException
DuplicateAccessPointNameException = exceptions.DuplicateAccessPointNameException
DuplicateListenerException = exceptions.DuplicateListenerException
DuplicatePolicyNameException = exceptions.DuplicatePolicyNameException
DuplicateTagKeysException = exceptions.DuplicateTagKeysException
InvalidConfigurationRequestException = exceptions.InvalidConfigurationRequestException
InvalidEndPointException = exceptions.InvalidEndPointException
InvalidSchemeException = exceptions.InvalidSchemeException
InvalidSecurityGroupException = exceptions.InvalidSecurityGroupException
InvalidSubnetException = exceptions.InvalidSubnetException
ListenerNotFoundException = exceptions.ListenerNotFoundException
LoadBalancerAttributeNotFoundException = exceptions.LoadBalancerAttributeNotFoundException
OperationNotPermittedException = exceptions.OperationNotPermittedException
PolicyNotFoundException = exceptions.PolicyNotFoundException
PolicyTypeNotFoundException = exceptions.PolicyTypeNotFoundException
SubnetNotFoundException = exceptions.SubnetNotFoundException
TooManyAccessPointsException = exceptions.TooManyAccessPointsException
TooManyPoliciesException = exceptions.TooManyPoliciesException
TooManyTagsException = exceptions.TooManyTagsException
UnsupportedProtocolException = exceptions.UnsupportedProtocolException
