import boto3

exceptions = boto3.client('events').exceptions

ConcurrentModificationException = exceptions.ConcurrentModificationException
InternalException = exceptions.InternalException
InvalidEventPatternException = exceptions.InvalidEventPatternException
InvalidStateException = exceptions.InvalidStateException
LimitExceededException = exceptions.LimitExceededException
ManagedRuleException = exceptions.ManagedRuleException
PolicyLengthExceededException = exceptions.PolicyLengthExceededException
ResourceAlreadyExistsException = exceptions.ResourceAlreadyExistsException
ResourceNotFoundException = exceptions.ResourceNotFoundException
