import boto3

exceptions = boto3.client('kinesisanalyticsv2').exceptions

CodeValidationException = exceptions.CodeValidationException
ConcurrentModificationException = exceptions.ConcurrentModificationException
InvalidApplicationConfigurationException = exceptions.InvalidApplicationConfigurationException
InvalidArgumentException = exceptions.InvalidArgumentException
InvalidRequestException = exceptions.InvalidRequestException
LimitExceededException = exceptions.LimitExceededException
ResourceInUseException = exceptions.ResourceInUseException
ResourceNotFoundException = exceptions.ResourceNotFoundException
ResourceProvisionedThroughputExceededException = exceptions.ResourceProvisionedThroughputExceededException
ServiceUnavailableException = exceptions.ServiceUnavailableException
TooManyTagsException = exceptions.TooManyTagsException
UnableToDetectSchemaException = exceptions.UnableToDetectSchemaException
UnsupportedOperationException = exceptions.UnsupportedOperationException
