import boto3

exceptions = boto3.client('kms').exceptions

AlreadyExistsException = exceptions.AlreadyExistsException
CloudHsmClusterInUseException = exceptions.CloudHsmClusterInUseException
CloudHsmClusterInvalidConfigurationException = exceptions.CloudHsmClusterInvalidConfigurationException
CloudHsmClusterNotActiveException = exceptions.CloudHsmClusterNotActiveException
CloudHsmClusterNotFoundException = exceptions.CloudHsmClusterNotFoundException
CloudHsmClusterNotRelatedException = exceptions.CloudHsmClusterNotRelatedException
CustomKeyStoreHasCMKsException = exceptions.CustomKeyStoreHasCMKsException
CustomKeyStoreInvalidStateException = exceptions.CustomKeyStoreInvalidStateException
CustomKeyStoreNameInUseException = exceptions.CustomKeyStoreNameInUseException
CustomKeyStoreNotFoundException = exceptions.CustomKeyStoreNotFoundException
DependencyTimeoutException = exceptions.DependencyTimeoutException
DisabledException = exceptions.DisabledException
ExpiredImportTokenException = exceptions.ExpiredImportTokenException
IncorrectKeyMaterialException = exceptions.IncorrectKeyMaterialException
IncorrectTrustAnchorException = exceptions.IncorrectTrustAnchorException
InvalidAliasNameException = exceptions.InvalidAliasNameException
InvalidArnException = exceptions.InvalidArnException
InvalidCiphertextException = exceptions.InvalidCiphertextException
InvalidGrantIdException = exceptions.InvalidGrantIdException
InvalidGrantTokenException = exceptions.InvalidGrantTokenException
InvalidImportTokenException = exceptions.InvalidImportTokenException
InvalidKeyUsageException = exceptions.InvalidKeyUsageException
InvalidMarkerException = exceptions.InvalidMarkerException
KMSInternalException = exceptions.KMSInternalException
KMSInvalidStateException = exceptions.KMSInvalidStateException
KeyUnavailableException = exceptions.KeyUnavailableException
LimitExceededException = exceptions.LimitExceededException
MalformedPolicyDocumentException = exceptions.MalformedPolicyDocumentException
NotFoundException = exceptions.NotFoundException
TagException = exceptions.TagException
UnsupportedOperationException = exceptions.UnsupportedOperationException
