import boto3

exceptions = boto3.client('polly').exceptions

EngineNotSupportedException = exceptions.EngineNotSupportedException
InvalidLexiconException = exceptions.InvalidLexiconException
InvalidNextTokenException = exceptions.InvalidNextTokenException
InvalidS3BucketException = exceptions.InvalidS3BucketException
InvalidS3KeyException = exceptions.InvalidS3KeyException
InvalidSampleRateException = exceptions.InvalidSampleRateException
InvalidSnsTopicArnException = exceptions.InvalidSnsTopicArnException
InvalidSsmlException = exceptions.InvalidSsmlException
InvalidTaskIdException = exceptions.InvalidTaskIdException
LanguageNotSupportedException = exceptions.LanguageNotSupportedException
LexiconNotFoundException = exceptions.LexiconNotFoundException
LexiconSizeExceededException = exceptions.LexiconSizeExceededException
MarksNotSupportedForFormatException = exceptions.MarksNotSupportedForFormatException
MaxLexemeLengthExceededException = exceptions.MaxLexemeLengthExceededException
MaxLexiconsNumberExceededException = exceptions.MaxLexiconsNumberExceededException
ServiceFailureException = exceptions.ServiceFailureException
SsmlMarksNotSupportedForTextTypeException = exceptions.SsmlMarksNotSupportedForTextTypeException
SynthesisTaskNotFoundException = exceptions.SynthesisTaskNotFoundException
TextLengthExceededException = exceptions.TextLengthExceededException
UnsupportedPlsAlphabetException = exceptions.UnsupportedPlsAlphabetException
UnsupportedPlsLanguageException = exceptions.UnsupportedPlsLanguageException
