import boto3

exceptions = boto3.client('ram').exceptions

IdempotentParameterMismatchException = exceptions.IdempotentParameterMismatchException
InvalidClientTokenException = exceptions.InvalidClientTokenException
InvalidMaxResultsException = exceptions.InvalidMaxResultsException
InvalidNextTokenException = exceptions.InvalidNextTokenException
InvalidParameterException = exceptions.InvalidParameterException
InvalidResourceTypeException = exceptions.InvalidResourceTypeException
InvalidStateTransitionException = exceptions.InvalidStateTransitionException
MalformedArnException = exceptions.MalformedArnException
MissingRequiredParameterException = exceptions.MissingRequiredParameterException
OperationNotPermittedException = exceptions.OperationNotPermittedException
ResourceArnNotFoundException = exceptions.ResourceArnNotFoundException
ResourceShareInvitationAlreadyAcceptedException = exceptions.ResourceShareInvitationAlreadyAcceptedException
ResourceShareInvitationAlreadyRejectedException = exceptions.ResourceShareInvitationAlreadyRejectedException
ResourceShareInvitationArnNotFoundException = exceptions.ResourceShareInvitationArnNotFoundException
ResourceShareInvitationExpiredException = exceptions.ResourceShareInvitationExpiredException
ResourceShareLimitExceededException = exceptions.ResourceShareLimitExceededException
ServerInternalException = exceptions.ServerInternalException
ServiceUnavailableException = exceptions.ServiceUnavailableException
TagLimitExceededException = exceptions.TagLimitExceededException
TagPolicyViolationException = exceptions.TagPolicyViolationException
UnknownResourceException = exceptions.UnknownResourceException
