import boto3

exceptions = boto3.client('sns').exceptions

AuthorizationErrorException = exceptions.AuthorizationErrorException
EndpointDisabledException = exceptions.EndpointDisabledException
FilterPolicyLimitExceededException = exceptions.FilterPolicyLimitExceededException
InternalErrorException = exceptions.InternalErrorException
InvalidParameterException = exceptions.InvalidParameterException
InvalidParameterValueException = exceptions.InvalidParameterValueException
InvalidSecurityException = exceptions.InvalidSecurityException
KMSAccessDeniedException = exceptions.KMSAccessDeniedException
KMSDisabledException = exceptions.KMSDisabledException
KMSInvalidStateException = exceptions.KMSInvalidStateException
KMSNotFoundException = exceptions.KMSNotFoundException
KMSOptInRequired = exceptions.KMSOptInRequired
KMSThrottlingException = exceptions.KMSThrottlingException
NotFoundException = exceptions.NotFoundException
PlatformApplicationDisabledException = exceptions.PlatformApplicationDisabledException
SubscriptionLimitExceededException = exceptions.SubscriptionLimitExceededException
ThrottledException = exceptions.ThrottledException
TopicLimitExceededException = exceptions.TopicLimitExceededException
