import boto3

exceptions = boto3.client('sts').exceptions

ExpiredTokenException = exceptions.ExpiredTokenException
IDPCommunicationErrorException = exceptions.IDPCommunicationErrorException
IDPRejectedClaimException = exceptions.IDPRejectedClaimException
InvalidAuthorizationMessageException = exceptions.InvalidAuthorizationMessageException
InvalidIdentityTokenException = exceptions.InvalidIdentityTokenException
MalformedPolicyDocumentException = exceptions.MalformedPolicyDocumentException
PackedPolicyTooLargeException = exceptions.PackedPolicyTooLargeException
RegionDisabledException = exceptions.RegionDisabledException
