import boto3

exceptions = boto3.client('workdocs').exceptions

ConcurrentModificationException = exceptions.ConcurrentModificationException
ConflictingOperationException = exceptions.ConflictingOperationException
CustomMetadataLimitExceededException = exceptions.CustomMetadataLimitExceededException
DeactivatingLastSystemUserException = exceptions.DeactivatingLastSystemUserException
DocumentLockedForCommentsException = exceptions.DocumentLockedForCommentsException
DraftUploadOutOfSyncException = exceptions.DraftUploadOutOfSyncException
EntityAlreadyExistsException = exceptions.EntityAlreadyExistsException
EntityNotExistsException = exceptions.EntityNotExistsException
FailedDependencyException = exceptions.FailedDependencyException
IllegalUserStateException = exceptions.IllegalUserStateException
InvalidArgumentException = exceptions.InvalidArgumentException
InvalidCommentOperationException = exceptions.InvalidCommentOperationException
InvalidOperationException = exceptions.InvalidOperationException
InvalidPasswordException = exceptions.InvalidPasswordException
LimitExceededException = exceptions.LimitExceededException
ProhibitedStateException = exceptions.ProhibitedStateException
RequestedEntityTooLargeException = exceptions.RequestedEntityTooLargeException
ResourceAlreadyCheckedOutException = exceptions.ResourceAlreadyCheckedOutException
ServiceUnavailableException = exceptions.ServiceUnavailableException
StorageLimitExceededException = exceptions.StorageLimitExceededException
StorageLimitWillExceedException = exceptions.StorageLimitWillExceedException
TooManyLabelsException = exceptions.TooManyLabelsException
TooManySubscriptionsException = exceptions.TooManySubscriptionsException
UnauthorizedOperationException = exceptions.UnauthorizedOperationException
UnauthorizedResourceAccessException = exceptions.UnauthorizedResourceAccessException
